theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  plausible: lesveteransduweb.org
  posts:
    index:
      layout: grid